[tool.poetry]
name = "rvc-enhanced"
version = "0.1.0"
description = ""
authors = ["coming <kangming06@hotmail.com>"]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
